---
- name: Install Docker on app hosts
  hosts: app
  become: true
  roles:
    - docker
    
- name: Deploy Django application on hosts
  hosts: app
  become: true
  roles:
    - django_deploy

- name: Setup Nginx
  hosts: web
  become: true
  roles:
    - nginx
