- name: Install OpenVPN
  apt:
    name: openvpn
    state: present
    update_cache: yes

- name: Configure OpenVPN server
  template:
    src: openvpn.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: '0644'

- name: Start OpenVPN service
  systemd:
    name: openvpn@server
    state: started
    enabled: yes

- name: Generate client config file
  command: "bash /etc/openvpn/easy-rsa/easyrsa gen-req {{ openvpn_client_name }} nopass"
  args:
    creates: "/etc/openvpn/pki/private/{{ openvpn_client_name }}.key"

- name: Create .ovpn client configuration file
  template:
    src: client.ovpn.j2
    dest: "{{ playbook_dir }}/{{ openvpn_client_name }}.ovpn"
